# Generated by Django 3.1.2 on 2020-12-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='UserName',
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, default=8, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
