# Generated by Django 3.1.2 on 2020-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0004_auto_20201206_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='title')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
