# Generated by Django 3.1.2 on 2020-12-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0005_auto_20201207_0302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllUsers',
            new_name='AllUser',
        ),
    ]
